### ISSUE TITLE
Build Shashlik

### ISSUE THREAD

**Issue by stephdgenius** [shashlik/shashlik-build#16]
How to build shashlik with fork-frameworks-base, fork-qemu, shashlik-runtime-env and shashlikd ?

**Comment by davidedmundson** [comment]
See instructions on shashlik.io

**Comment by stephdgenius** [comment]
Are the other files (android-libhardware, fork-frameworks-based, fork-qemu, shashlik-build, shashlikd, shashlik-runtime-env) on Github are also useful for the compilation  ? because I have download the all source code of shashlik
