### ISSUE TITLE
Please upload Debian tarball, or explain build process better

### ISSUE THREAD

**Issue by mdeguzis** [shashlik/shashlik-build#22]
See the latest comments on your web page: http://www.shashlik.io/what-is/

It is getting very hard to figure out how to exactly build this thing, can this be corrected? At the very least, can you please upload the debian tarball so we can see how the debs for Ubuntu are built?

See comment:
http://www.shashlik.io/what-is/#comment-2597916806

**Comment by davidedmundson** [comment]
The only debian file is the control file which you can get from the .deb

the rest was built with debuild.

**Comment by mdeguzis** [comment]
So the build process will remain a mystery? Can you explain the errors? Judging by how quickly you closed this, I suppose not. The build instructions on the wiki vs. the about page on the main site are different. If the main site is wrong, it would help if they were updated then.

**Comment by davidedmundson** [comment]
what wiki?

**Comment by mdeguzis** [comment]
https://github.com/shashlik/old-shashlik/wiki/Building , and I use pdebuild, which uses debuild anyway, still getting the errors listed in comments on the about page of Shashlik.io. Also, your control file didn't seem to list build deps as well when I checked yesterday with `ar -x pkg.deb`.  The about page build process also does not list what packages in general are needed. I'll try once more with plain debuild.

**Comment by davidedmundson** [comment]
Yeah, anything with "old-" in the repo name is outdated.

**Comment by mdeguzis** [comment]
Same error with straight debuild: [log](https://gist.github.com/ProfessorKaos64/c8769b74bafb0515cbd5b8d18ae550bf). This is what a lot of people get, since we don't know the specific build steps. That piece of code is in `build/core/soong.mk`
