### ISSUE TITLE
Doesn't install Shashlik on Linux Mint 17.3 with Cinnamon!

### ISSUE THREAD

**Issue by ciberperipecias** [shashlik/shashlik-build#23]
Hi! There's a problem on installing Shashlik on Linux Mint 17.3 with Cinnamon. After download the .deb package on http://www.shashlik.io/download/, I used GDebi to install as usual and after Terminal done the installation nothing had happen. The program isn't on Menu, and on Terminal too. Is there a problem with the Shashlik on Linux Mint at the moment?

![download site on 27-04-2016](https://cloud.githubusercontent.com/assets/18706178/14864174/1445f910-0c8f-11e6-914c-92ecce5cab72.png)

![terminal results](https://cloud.githubusercontent.com/assets/18706178/14864031/95ec605e-0c8e-11e6-807d-457ff2b5140d.png)

**Comment by davidedmundson** [comment]
We don't install anything in $path. See the rest of the tutorial in the tutorial.
