### ISSUE TITLE
shashlik works only at first run

### ISSUE THREAD

**Issue by ghost** [shashlik/shashlik-build#33]
Hi.

Shashlik works only at first run, after that black screen with buttons. I've forced to remove ~/.local/share/shashlik/userdata.img to make it work one more time.

How to make it work correctly?

cast @davidedmundson 

Thanks.

**Comment by ghost** [comment]
Seen for example with shashlik 0.9.3 under Kubuntu 16.04.1 LTS
https://github.com/shashlik/shashlik-build/issues/2#issuecomment-235069662 doesn't help

**Comment by gladstonedigital** [comment]
I'm having this same problem; I thought it was just something I was doing wrong. Any solution?
