### ISSUE TITLE
Deploys into running Android emulator

### ISSUE THREAD

**Issue by scic** [shashlik/shashlik-build#5]
If you already have an android emulator running (e.g. launched from Android Studio), it will open the app inside that emulator. It works in there. But it should launch its own instance of the emulator.

**Comment by davidedmundson** [comment]
Thanks, it's something that's going to be fixed in the next build

**Comment by davidedmundson** [comment]
0.9.4 should fix this

**Comment by licaon-kter** [comment]
@davidedmundson Do update release info too: https://github.com/shashlik/shashlik-build/releases
