### ISSUE TITLE
problem running apk in Debian testing

### ISSUE THREAD

**Issue by fapasv** [shashlik/shashlik-build#9]
## (I'm running virtualbox at the same time.) 

`starting emulator`
`emulator: WARNING: system partition size adjusted to match image file (750 MB > 200 MB)`
`emulator: WARNING: data partition size adjusted to match image file (750 MB > 200 MB)`
`setting icon3`
`setting icon1`
`setting icon`
`Creating filesystem with parameters:`
 `Size: 69206016`
`Block size: 4096`
`Blocks per group: 32768`
`Inodes per group: 4224`
`Inode size: 256`
`Journal blocks: 1024`
`Label:`
`Blocks: 16896`
`Block groups: 1`
`Reserved block group size: 7`
`Created filesystem with 11/4224 inodes and 1302/16896 blocks`
`i1octl(KVM_CREATE_VM) failed: 16 Device or resource busy`
`ko:failed to initialize KVM`

**Comment by licaon-kter** [comment]
Maybe change _VirtualBox -> `machine` -> Settings -> System -> Acceleration -> Paravirt_ to something else other than KVM and Default ?

**Comment by fapasv** [comment]
thx man!

**Comment by licaon-kter** [comment]
Which one did it?
